### ISSUE TITLE
Makefile: Pretty version

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#141]
Ideally, what would be nice is to have the `VERSION` variable in the Makefile be set according to the following rules:

IF the current commit ID has an associated tag, VERSION should be set to that tag: `1.0.1`

IF the current version ID does not have a tag, VERSION should be set to the last tag plus a "build id" with the short commit: `1.0.1+ee45c49f`

Since the build ID is not considered significant by SemVer 2, users will never be prompted to update based on Git commit alone. This also allows us to use `-alpha` and `-beta` in tags, while still remaining SemVer 2 compliant.

And most importantly, official releases will look pretty `version: 1.0.1`, while dev environments will have build info conveniently embedded in the version.

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this enhancement request.
