### ISSUE TITLE
Special handling for symlinks on fetch

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#16]
From #8 @BVrolyk points out that we need to watch for loops and other nasty conditions if a Chart has a symlink.

**Comment by technosophos** [comment]
Right now, helm won't follow symlinks that well. We should decide to what extent we want Helm to follow links. cf #249

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this issue.
