### ISSUE TITLE
Service race condition? (Unobserved, but theoretically possible)

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#192]
There is a possible race condition when a service is deployed, and then a pod or rc that depends on that service is deployed. If the service is not running, the pod/rc may not get the appropriate environment variables.

The solution would be to deploy a service, and then wait until the service is in state RUNNING (?).

**Comment by jchauncey** [comment]
see #236

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this issue.
