### ISSUE TITLE
Feature: Helm-Monitor (or helmd)

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#193]
@kelseyhightower suggested that we could run an in-Kubernetes monitor that would keep its own copy of the charts repo, and notify users when the in-cluster charts are out of date. At some point it could even deploy updated charts.

Monitoring functionality could be as simple as watching the version annotations on anything with the label `heritage:deis`.

**Comment by rimusz** [comment]
+1

**Comment by mattfarina** [comment]
You could take this a step further and provide a report. Something like https://david-dm.org/ (see an example at https://david-dm.org/bower/bower). Not just updates but version and security issues.

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this proposal.
