### ISSUE TITLE
Proposal: Extended dependency declarations

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#195]
Currently we have dependency declarations like this:

```
depends:
  - name: redis    # chart name
    version: ~1.3  # semver version or range
```

We need to extend the dependency system to support `provider` support. (For info on providers, see https://github.com/deis/helm/blob/master/docs/using_labels.md)

One method of doing this is to extend the `depends` structure to have the following fields:

- `type`: One of `provider` or `chart`, with `chart` being the default.
- `name`: The name. Required by `type:chart`, optional on `type:provider`
- `version`: A SemVer range, applicable only to `type: chart`
- `selector`: A label selector (http://kubernetes.io/v1.0/docs/user-guide/labels.html), used only by `type: provider`

**Comment by bacongobbler** [comment]
Given the following use case with this proposal:

 - I have a chart named foo
 - foo requires a mysql chart
 - in my charts I have `mysql` and `mysql-cluster`, both are mysql providers

How would `helm install foo` work when there's a provider collision?

> type: One of provider or chart, with chart being the default.

Is there a use case when we would want our chart to be dependent on another chart?

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this proposal. 🚪
