### ISSUE TITLE
Fetch --all grabs dependencies

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#270]
Right now, dependency resolution works like this:

- fetch grabs a chart, and checks the direct dependencies
- if the dependencies are not satisfied, it emits a warning

And install works similarly:

- install grabs a chart and checks its direct dependencies
- if the dependencies are not satisfied, install fails (unless --force is specified, then install proceeds)

This issue augments these behaviors with a `--all` flag. If specified, then both `fetch` and `install` will fetch all of the unsatisfied dependencies into the workspace. This is done recursively. Any failed fetch will result in stopping the entire process.

For install, all of the dependencies will also be installed into k8s.

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this enhancement request.
