### ISSUE TITLE
Post-install sanity check

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#274]
After install, we can add an (optional?) check to make sure that all manifests we installed resulted in created resources.

**Comment by arschles** [comment]
+1

**Comment by gabrtv** [comment]
:+1: I think this is the best solution for handling Kubernetes dependencies and Kube resources that may not be available in a given cluster.

**Comment by rimusz** [comment]
:+1:

**Comment by technosophos** [comment]
Keep in mind that a check could take more than 10 minutes (easily) if pods or rcs need to pull multiple images. So this could be a heavy requirement to enable by default.

**Comment by gabrtv** [comment]
@technosophos I was envisioning we would check for resource creation and not necessarily wait for resources to go into a running/ready state.  In this case, we wouldn't need to wait for image pulls.

**Comment by arschles** [comment]
@technosophos I assumed you meant a check for services, pods, rcs, etc... are up, not ensuring that pods are `RUNNING`. agree that the latter check should be off by default

**Comment by technosophos** [comment]
Oh, yeah.... that we could do  in a timely manner.

**Comment by arschles** [comment]
oh, I just repeated what @gabrtv said. should have read up :facepalm:

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this enhancement request.
