### ISSUE TITLE
should we use `install` to upgrade to a new Chart version, or should we have an 'upgrade' command?

### ISSUE THREAD

**Issue by jstrachan** [helm/helm-classic#292]
I just realised there wasn't an `upgrade` command (like `brew upgrade`) and wondered if this was intentional.

Is the idea that you re-run `helm install` whenever charts update? e.g.

```
helm install cheese
# time passes and new verisons of charts arrive

helm update
helm install cheese
```

Or should the second `install` fail as its already installed and the `upgrade` command should be used to apply upgrades where you need to specify the policy (e.g. destroy then recreate, merge, rolling upgrade etc). 

```
helm install cheese
# time passes and new verisons of charts arrive

helm update
helm upgrade cheese rolling
```

Relates to #1

**Comment by jstrachan** [comment]
kubectl has options `create`, `update`, `replace`; with a force mode for `update` then for RCs its got `rolling-update` so I wonder if a new `upgrade` command needs to wrap up these different ways of doing an upgrade?

**Comment by jstrachan** [comment]
I've tried implementing this in the openshift-all branch here: https://github.com/fabric8io/helm/tree/openshift-all which has all the PRs merged together. It seems to be working pretty reasonably. 

So you can do
```
helm update
helm upgrade foo
```
which then effectively does a `kubectl apply -f ....` on each resource to update it.

I can cherry pick this to a clean master branch and submit a PR if you fancy it?

**Comment by jstrachan** [comment]
incidentally it seems that `kubectl update` is deprecated and `kubectl replace` is the long term replacement; which only works if the kube resource is complete with its full runtime spec and resourceVersion etc. So its a little tricky to use from helm directly from a chart's resources; we'd have to get the current JSON/YAML and merge in place the resource from the chart. 

So I've switched to using `kubectl apply` which is much more forgiving; though you do need to set the `resourceVersion`. Its working at least ;)

I wonder if its worth renaming `helm upgrade` to `helm apply`? As right now the logic either creates or applies changes depending on if each resource is installed or not. e.g. a new version of a chart might add a new update an existing RC but add a new service or RC; so being able to create or apply on a per resource basis based on whats already installed will be really handy. 

Its just a question of what we call the helm command though ;). 'upgrade' does seem brew-ish at least

**Comment by technosophos** [comment]
This was on our roadmap to figure out, so thank you for jumping in on this. I like the way you've approached it. It feels right from a user perspective.

Even though I like the word `upgrade` better, I personally would lean toward re-using the Kube verbs just so it's more likely that our users will make the right assumptions about what's happening. So `helm apply` is probably better.

Thoughts, @gabrtv?

**Comment by gabrtv** [comment]
+1 for `helm apply`.  It maps to the underlying Kube semantics and also sends a signal that we're not venturing into the realm of orchestrated upgrades -- something that's definitely out of scope for us.

**Comment by technosophos** [comment]
@jstrachan we'd like to add this to the 0.3 milestone (~2-3 weeks out). Is that a reasonable time frame for you to cherry pick and PR?

**Comment by jstrachan** [comment]
on `helm upgrade` versus `helm apply` one thing I've found is that sometimes a new version of a chart has a new RC or service or something. The default behavior of `kubectl apply` is to barf if the resource doesn't already exist; so right now the logic of `helm update` is to either use `kubectl create` or `kubectl apply` depending on whether the resource exists or not. So its not quite a 1-1 mapping between `helm upgrade/apply` and `kubectl apply` depending on whats inside kubernetes.

Though I'm happy to go with `apply` despite this; as it does feel like `apply` should create or update depending on whats been installed

**Comment by jstrachan** [comment]
@technophos BTW I should be able to rebase & submit a PR soon...

**Comment by technosophos** [comment]
@jstrachan Now that you've explained it that way, maybe `helm update` is the better term.

**Comment by jstrachan** [comment]
yeah, I'm kinda on the fence - happy with either approach ;)

**Comment by mboersma** [comment]
In Helm classic, this was implemented by using the `helm-keep` annotation in combination with `helmc uninstall && helmc install`.
