### ISSUE TITLE
Move helm lint rules into a config file

### ISSUE THREAD

**Issue by sgoings** [helm/helm-classic#307]
As a user of `helm lint` I'd like to add additional lint rules via a lint configuration file so that I don't have to modify the helm project/binary directly when adding rules that might only apply to my internal organization's setup of helm charts.

**Comment by technosophos** [comment]
Could you give some examples? Is this the kind of thing where they are simple and declarative, or where we'd need something like a Lua interpreter?

**Comment by sgoings** [comment]
Haven't thought it out completely... but some ideas are:

- `heritage: helm` vs `heritage: X`
- image hierarchies limited to being from a specific org?

**Comment by arschles** [comment]
a few others that would help me, could be they don't belong in lint though:

- ensure a specific tag on all images (or tag that matches a regex)
- ensure a specific selector & label across an RC/pod and service
- ensure all ports within a range
- ensure service/RC/pod/port names all match a regex

also, I'm 100% behind keeping these declarative

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this proposal.
