### ISSUE TITLE
why does helm require a remote called `origin` in the cache directory?

### ISSUE THREAD

**Issue by arschles** [helm/helm-classic#347]
for example, I have a `deis/deis` repo added in my helm cache:

```console
ENG000656:deis aaronschlesinger$ pwd
/Users/aaronschlesinger/.helm/cache/deis
ENG000656:deis aaronschlesinger$ git remote -v
arschles	git@github.com:arschles/charts-1.git (fetch)
arschles	git@github.com:arschles/charts-1.git (push)
deis	https://github.com/deis/charts (fetch)
deis	https://github.com/deis/charts (push)
```

and `helm fetch deis/deis` complains that I don't have an `origin` (but still works). should this be required for `fetch`?

```console
ENG000656:deis aaronschlesinger$ helm fetch deis/deis
[ERROR] Git failed to get the origin name: exit status 1 
---> Fetched chart into workspace /Users/aaronschlesinger/.helm/workspace/charts/deis
---> Done
```

**Comment by technosophos** [comment]
It uses origin to look for the canonical name of the upstream Git repo. It uses that to resolve dependency issues.

https://github.com/helm/helm/blob/4cefaa5057930494cd5383eeb2a5e0f8bd8d201f/chart/chartfile.go#L54

**Comment by arschles** [comment]
got it, thanks. would it be possible to make the remote name configurable?

**Comment by technosophos** [comment]
I think we could make it configurable in the `config.yaml` file, and then add a nice CLI flag for `helm repo add`.

**Comment by technosophos** [comment]
Should we re-title this and mark it as an enhancement instead of a question?

**Comment by arschles** [comment]
done

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this enhancement request.
