### ISSUE TITLE
Deployment k8s objects cannot be installed with helm

### ISSUE THREAD

**Issue by spiddy** [helm/helm-classic#456]
When trying to install a _Deployment_ k8s object I get the following error:

```
➜  helm install nginx
---> Running `kubectl create -f` ...
error validating "STDIN": error validating data: API version "" isn't supported, only supports API versions ["extensions/v1beta1" "componentconfig/v1alpha1" "batch/v1" "autoscaling/v1" "authorization.k8s.io/v1beta1" "v1" "metrics/v1alpha1"]; if you choose to ignore these errors, turn validation off with --validate=false
```

The deployment object is taken from the helm test sample:

```
➜ cat ~/.helm/workspace/charts/nginx/manifests/example-pod.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

The dry-run shows that the object is not read properly from file:

```
➜  helm install nginx --dry-run
---> Running `kubectl create -f` ...
[CMD] kubectl create -f - < {}
---> Done
========================================
# nginx

Describe your chart here. Link to upstream repositories, Docker images or any
external documentation.

If your application requires any specific configuration like Secrets, you may
include that information here.
========================================
```

helm compiled from `c983f0a` commit.

**Comment by spiddy** [comment]
Related to #426

**Comment by spiddy** [comment]
Related also to #255

**Comment by bacongobbler** [comment]
hi @spiddy, see the notice at https://github.com/helm/helm#helm-classic---the-original-kubernetes-package-manager. This project is on life support until kubernetes/helm has stabilized.

**Comment by spiddy** [comment]
@bacongobbler thanks, I'm aware, but still need a solution until kubernetes/helm is released.

Though, I'm not sure if kubernetes/helm can cover all use-cases of helm-classic. I understand that the architecture of k8s-helm is to use server-side services for managing releases. What if I don't want to alter the k8s, but still want a client-side package management?

**Comment by krancour** [comment]
@bacongobbler I'm heading up the "Helm Classic" effort and I would agree with @spiddy that until k8s/helm is stable and ready for prime time, minor improvement like this count as "life support."  I don't see this as a feature so much as a fix for something that's missing.

(fwiw, the rationale by which I would consider deployment "missing," is that Workflow requires k8s 1.2 _and_ requires "Helm Classic" for installation.  So implicitly, "Helm Classic" supports k8s 1.2.  Deployments are in the `extensions/v1beta1` API, which, in contrast to 1.1, k8s 1.2 enables by default.  So anything in 1.2 that "Helm Classic" chokes on should really be fixed, IMO.)

**Comment by krancour** [comment]
Per my rationale above, I'm actually going to classify this as a bug.

**Comment by rimusz** [comment]
@krancour can we cut the helmc release ASAP as Deployments support is really need for trainings/workshops in my case.

**Comment by krancour** [comment]
@rimusz we could... but also, I believe that deployments (specifically) are not the only k8s 1.2 resource types that aren't handled. For instance, #461 documents current lack of support for ConfigMaps.

I think what we really need to do is identify _all_ of what's missing and get those things added, rather than add support for just one (deployments) and then cut a release.

Think you'd be willing to figure what's missing and perhaps submit on PR to fill in all of those blanks?

**Comment by rimusz** [comment]
@krancour I think the ConfigMaps is another which needs support in helm classic.
But as we have deployments in the master already and the binary is already built via CI build pipeline I do not see any blockers to get release promoted to stable and then we can figure out configMaps support.

**Comment by krancour** [comment]
@mboersma do you have thoughts on this?  I know you've got a new feature into master and are sooner or later wanting to release Helm Classic 0.8.0.

**Comment by mboersma** [comment]
> sooner or later wanting to release Helm Classic 0.8.0.

I would like to release Helm Classic 0.8.0 by next Monday 5/23, so the `helm-keep` annotation can be used in the Deis Workflow beta4 Chart. But we can wait until the last minute to see if any other (backward-compatible, semver-compliant) features or fixes land.

**Comment by krancour** [comment]
@rimusz so you'll get a release that includes deployment support on Monday.

**Comment by rimusz** [comment]
@krancour awesome
