### ISSUE TITLE
Unable to download helmc due to 403s from bintray.com

### ISSUE THREAD

**Issue by jgmize** [helm/helm-classic#482]
All of the links on https://bintray.com/deis/helm-ci/helmc/0.8.0%2Be4b3983/view#files and https://bintray.com/deis/helm/helmc/0.8.1%2Be4b3983/view#files give me a 403 forbidden. This also breaks the `curl -sSL https://get.helm.sh | bash` install flow.

**Comment by jgmize** [comment]
This applies to the older versions at https://bintray.com/deis/helm-ci/helmc/0.7.0%2B7a00a0c/view#files and https://bintray.com/deis/helm/helmc/0.7.0%2B20a7ed7/view#files as well.

**Comment by arkkanoid** [comment]
+1

**Comment by bacongobbler** [comment]
I have a feeling that this is from the recent notice we got from bintray last night:

> Hi Deis,

> Your Bintray account is currently rate-limited due to overuse.
Customer Support should contact you at the earliest to remove the limits from your account. You may also contact them directly at support@bintray.com.

> Regards,
> The Bintray Team

**Comment by bacongobbler** [comment]
In the meantime, you can compile the client from source via https://github.com/helm/helm-classic#building-the-helm-classic-cli

**Comment by sgoings** [comment]
I'm working on an immediate solution with Bintray at the moment.

**Comment by mboersma** [comment]
The heroics mentioned above have restored bintray access.
