### ISSUE TITLE
Error running helmc generate --force on v0.8.1+e4b3983

### ISSUE THREAD

**Issue by arkkanoid** [helm/helm-classic#483]
The first time I run helmc generate it works. If I re-run the command it fails:

    helmc generate -x --force manifests workflow-rc1
    Failed to complete generation: lstat /home/XXX/.helmc/workspace/charts/manifests: no such file or directory

**Comment by mboersma** [comment]
The `-x` flag takes `manifests` as its argument. So this should be:
```
helmc generate -x manifests --force workflow-rc1
```

**Comment by arkkanoid** [comment]
Working.
Thanks!
