### ISSUE TITLE
upload builds to S3

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-classic#484]
See reasoning behind this movement in https://github.com/deis/workflow/issues/282#issuecomment-224008617

Also, documentation and install scripts will need to be changed. See [deis/workflow](https://github.com/deis/workflow) for docs. The script's location has yet to be determined.

**Comment by arschles** [comment]
A Google Cloud Storage bucket has been created in the `deis-downloads` project at https://console.cloud.google.com/storage/browser/helm-classic/?project=deis-downloads

**Comment by arschles** [comment]
See https://github.com/deis/deisrel/pull/88 for an example implementation
