### ISSUE TITLE
Progress meter for long ops

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#6]
`helm update` could potentially take a long time. Could we get a progress meter for that?

**Comment by mboersma** [comment]
The deis CLI has a [`progress`](https://github.com/deis/deis/blob/29b6c0b2aab51739cd2a128f7fd5dbbb6b305809/client/cmd/utils.go#L15) func that could be used, which is a simplification of my [progress demo](https://github.com/mboersma/progress).

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this enhancement request.
