### ISSUE TITLE
`helm show` command

### ISSUE THREAD

**Issue by rimusz** [helm/helm-classic#61]
Shall we have e.g. `helm show` command, which would show the content of `charts` manifest files?

**Comment by technosophos** [comment]
Should we do this using the `edit` logic for concatenating the files, but then just dump to STDOUT instead of opening an editor? /cc @gabrtv

**Comment by rimusz** [comment]
@technosophos yes, that should good enough to check chart's manifest files /cc @gabrtv

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this enhancement request.
