### ISSUE TITLE
Make --group mandatory

### ISSUE THREAD

**Issue by slack** [helm/helm-classic#80]
We need to make sure folks who deploy more than one instance of a helm chart into a single namespace don't end up getting very confusing results.

For example, if I have two instances of `redis-standalone` in the `default` namespace and I use a simple label selector of `provider=redis` my application will be automatically load balanced between all redis instances.

We should probably make `group=...` parameter required.

**Comment by sgoings** [comment]
I think adding a required parameter reduces a bit of the magic that a `helm install` gives users. If at all possible, we should have default commands (with no parameters) that "just work."

**Comment by bgrant0607** [comment]
Why not just use separate namespaces?

Related: https://github.com/kubernetes/kubernetes/issues/1698

**Comment by gabrtv** [comment]
> Why not just use separate namespaces?

We do offer namespace parameterization. However, we also want to allow for multiple instances of a chart (Redis) to live in the same namespace.  The `group` label convention allows for multiple `provider`s to co-exist in the same namespace -- analogous to a `tier` label.

**Comment by technosophos** [comment]
I am not totally convinced that we need to make `group` mandatory for Helm to work. This imposes an unnecessary burden on the simple-case user. It also enforces a part of "our model" that not all users will find they want to participate in.

I'd rather develop more of a use case than rush to implement this as described here.

**Comment by bgrant0607** [comment]
I'm supportive of adding some automatic label management to Kubernetes. 

https://github.com/kubernetes/kubernetes/issues/15390

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kubernetes/helm). Helm Classic is in maintenance mode, so I'm closing this enhancement request.
